// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wechat$0 from "./wechat/models.js";

/**
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function ClipboardSetText(text) {
    return $Call.ByID(3696000683, text);
}

/**
 * ComputeSavePath 计算输出路径，根据平台自动使用正确的路径分隔符
 * @param {string} outputDir
 * @param {string} wxapkgPath
 * @returns {$CancellablePromise<string>}
 */
export function ComputeSavePath(outputDir, wxapkgPath) {
    return $Call.ByID(2357929225, outputDir, wxapkgPath);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDefaultPaths() {
    return $Call.ByID(64815741).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetWxapkgItem returns the latest state of the item by UUID (push-pull pattern)
 * @param {string} uuid
 * @returns {$CancellablePromise<wechat$0.WxapkgItem | null>}
 */
export function GetWxapkgItem(uuid) {
    return $Call.ByID(2545161513, uuid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Github() {
    return $Call.ByID(1456188945);
}

/**
 * @param {string} title
 * @param {string} root
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog(title, root) {
    return $Call.ByID(4083573141, title, root);
}

/**
 * @param {string} title
 * @param {string} root
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title, root, filters) {
    return $Call.ByID(3715902596, title, root, filters);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(2898191345, path);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenUrl(url) {
    return $Call.ByID(1321979035, url);
}

/**
 * @param {string} path
 * @param {boolean} scan
 * @returns {$CancellablePromise<wechat$0.WxapkgItem[]>}
 */
export function ScanWxapkgItem(path, scan) {
    return $Call.ByID(3568055588, path, scan).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetContext(app) {
    return $Call.ByID(4271854165, app);
}

/**
 * @param {wechat$0.WxapkgItem} item
 * @param {wechat$0.UnpackOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function UnpackWxapkgItem(item, options) {
    return $Call.ByID(3015806747, item, options);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(1828333558);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = wechat$0.WxapkgItem.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
