// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @typedef {string} StatusType
 */

export class UnpackOptions {
    /**
     * Creates a new UnpackOptions instance.
     * @param {Partial<UnpackOptions>} [$$source = {}] - The source object to create the UnpackOptions.
     */
    constructor($$source = {}) {
        if (!("EnableDecrypt" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["EnableDecrypt"] = false;
        }
        if (!("EnableJsBeautify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["EnableJsBeautify"] = false;
        }
        if (!("EnableHtmlBeautify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["EnableHtmlBeautify"] = false;
        }
        if (!("EnableJsonBeautify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["EnableJsonBeautify"] = false;
        }
        if (!("OutputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["OutputDir"] = "";
        }
        if (!("SavePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SavePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpackOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnpackOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnpackOptions(/** @type {Partial<UnpackOptions>} */($$parsedSource));
    }
}

export class WxapkgItem {
    /**
     * Creates a new WxapkgItem instance.
     * @param {Partial<WxapkgItem>} [$$source = {}] - The source object to create the WxapkgItem.
     */
    constructor($$source = {}) {
        if (!("UUID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UUID"] = "";
        }
        if (!("WxId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WxId"] = "";
        }
        if (!("Location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Location"] = "";
        }
        if (!("EncryptKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EncryptKey"] = "";
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }
        if (!("IsDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsDir"] = false;
        }
        if (!("LastModifyTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LastModifyTime"] = 0;
        }
        if (!("WxapkgFilePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["WxapkgFilePaths"] = [];
        }
        if (!("UnpackStatus" in $$source)) {
            /**
             * @member
             * @type {StatusType}
             */
            this["UnpackStatus"] = "";
        }
        if (!("UnpackCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["UnpackCurrent"] = 0;
        }
        if (!("UnpackTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["UnpackTotal"] = 0;
        }
        if (!("UnpackProgress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["UnpackProgress"] = 0;
        }
        if (!("UnpackCurrentFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UnpackCurrentFile"] = "";
        }
        if (!("UnpackSavePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UnpackSavePath"] = "";
        }
        if (!("UnpackErrorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UnpackErrorMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WxapkgItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WxapkgItem}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("WxapkgFilePaths" in $$parsedSource) {
            $$parsedSource["WxapkgFilePaths"] = $$createField7_0($$parsedSource["WxapkgFilePaths"]);
        }
        return new WxapkgItem(/** @type {Partial<WxapkgItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
